package main

import (
	"log"      // Logging package
	"net/http" // HTTP server package
	"os"       // Operating system functionality package
	"strings"  // String manipulation package

	_ "go-cashier-api/docs"

	"github.com/spf13/viper"                     // Configuration package
	httpSwagger "github.com/swaggo/http-swagger" // Swagger HTTP handler package

	// docs is generated by Swag CLI, you have to import it.

	"go-cashier-api/database" // Import database package
	"go-cashier-api/handler"  // Import handler package
	"go-cashier-api/repository"
	"go-cashier-api/service" // Import service package
)

type Config struct {
	Port   string `mapstructure:"PORT"`    // Server port
	DBConn string `mapstructure:"DB_CONN"` // Database connection string
}

// @title Go Cashier API
// @version 1.0
// @description This is a sample API for a cashier system.
// @BasePath /
func main() {
	viper.AutomaticEnv()                                   // read in environment variables
	viper.SetEnvKeyReplacer(strings.NewReplacer(".", "_")) // replace dots with underscores
	// Load .env file if it exists
	if _, err := os.Stat(".env"); err == nil {
		viper.SetConfigFile(".env")
		_ = viper.ReadInConfig()
	}

	// Map environment variables to Config struct
	config := Config{
		Port:   viper.GetString("PORT"),
		DBConn: viper.GetString("DBCONN"),
	}

	//Setup database connection
	db, err := database.InitDB(config.DBConn)
	if err != nil {
		log.Fatal("Failed to connect to database:", err)
	}
	defer db.Close()

	// Initialize repositories, services, and handlers for products
	productRepo := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepo)
	productHandler := handler.NewProductHandler(productService)

	// Initialize repositories, services, and handlers for categories
	categoryRepo := repository.NewCategoryRepository(db)
	categoryService := service.NewCategoryService(categoryRepo)
	categoryHandler := handler.NewCategoryHandler(categoryService)

	// Setup HTTP server and routes
	mux := http.NewServeMux()

	// Define routes and their handlers
	// Swagger endpoint
	mux.HandleFunc("/swagger/", httpSwagger.WrapHandler)
	// Health check endpoint
	mux.HandleFunc("/health", handler.HealthHandler)
	// API endpoints
	mux.HandleFunc("/api/products", productHandler.HandleProducts)
	mux.HandleFunc("/api/products/", productHandler.HandleProductByID)
	mux.HandleFunc("/api/categories", categoryHandler.HandleCategories)
	mux.HandleFunc("/api/categories/", categoryHandler.HandleCategoryByID)
	// Redirect root to Swagger UI
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/" {
			http.NotFound(w, r)
			return
		}
		http.Redirect(w, r, "/swagger/index.html", http.StatusTemporaryRedirect)
	})

	log.Println("Server running on :" + config.Port)
	log.Fatal(http.ListenAndServe(":"+config.Port, mux))
}
